export type PhoneCountry = {
  iso2: string;
  dialCode: string;
  nameEn: string;
  namePt: string;
  nameEs: string;
};

/** ITU calling codes ? sorted by country name (EN). */
export const PHONE_COUNTRIES: PhoneCountry[] = [
  { iso2: "AF", dialCode: "93", nameEn: "Afghanistan", namePt: "Afeganist?o", nameEs: "Afganist?n" },
  { iso2: "ZA", dialCode: "27", nameEn: "South Africa", namePt: "?frica do Sul", nameEs: "Sud?frica" },
  { iso2: "AL", dialCode: "355", nameEn: "Albania", namePt: "Alb?nia", nameEs: "Albania" },
  { iso2: "DE", dialCode: "49", nameEn: "Germany", namePt: "Alemanha", nameEs: "Alemania" },
  { iso2: "AD", dialCode: "376", nameEn: "Andorra", namePt: "Andorra", nameEs: "Andorra" },
  { iso2: "AO", dialCode: "244", nameEn: "Angola", namePt: "Angola", nameEs: "Angola" },
  { iso2: "SA", dialCode: "966", nameEn: "Saudi Arabia", namePt: "Ar?bia Saudita", nameEs: "Arabia Saudita" },
  { iso2: "DZ", dialCode: "213", nameEn: "Algeria", namePt: "Arg?lia", nameEs: "Argelia" },
  { iso2: "AR", dialCode: "54", nameEn: "Argentina", namePt: "Argentina", nameEs: "Argentina" },
  { iso2: "AM", dialCode: "374", nameEn: "Armenia", namePt: "Arm?nia", nameEs: "Armenia" },
  { iso2: "AU", dialCode: "61", nameEn: "Australia", namePt: "Austr?lia", nameEs: "Australia" },
  { iso2: "AT", dialCode: "43", nameEn: "Austria", namePt: "?ustria", nameEs: "Austria" },
  { iso2: "AZ", dialCode: "994", nameEn: "Azerbaijan", namePt: "Azerbaij?o", nameEs: "Azerbaiy?n" },
  { iso2: "BS", dialCode: "1242", nameEn: "Bahamas", namePt: "Bahamas", nameEs: "Bahamas" },
  { iso2: "BD", dialCode: "880", nameEn: "Bangladesh", namePt: "Bangladesh", nameEs: "Banglad?s" },
  { iso2: "BB", dialCode: "1246", nameEn: "Barbados", namePt: "Barbados", nameEs: "Barbados" },
  { iso2: "BH", dialCode: "973", nameEn: "Bahrain", namePt: "Bahrein", nameEs: "Bar?in" },
  { iso2: "BE", dialCode: "32", nameEn: "Belgium", namePt: "B?lgica", nameEs: "B?lgica" },
  { iso2: "BZ", dialCode: "501", nameEn: "Belize", namePt: "Belize", nameEs: "Belice" },
  { iso2: "BJ", dialCode: "229", nameEn: "Benin", namePt: "Benin", nameEs: "Ben?n" },
  { iso2: "BY", dialCode: "375", nameEn: "Belarus", namePt: "Bielorr?ssia", nameEs: "Bielorrusia" },
  { iso2: "BO", dialCode: "591", nameEn: "Bolivia", namePt: "Bol?via", nameEs: "Bolivia" },
  { iso2: "BA", dialCode: "387", nameEn: "Bosnia and Herzegovina", namePt: "B?snia e Herzegovina", nameEs: "Bosnia y Herzegovina" },
  { iso2: "BW", dialCode: "267", nameEn: "Botswana", namePt: "Botsuana", nameEs: "Botsuana" },
  { iso2: "BR", dialCode: "55", nameEn: "Brazil", namePt: "Brasil", nameEs: "Brasil" },
  { iso2: "BN", dialCode: "673", nameEn: "Brunei", namePt: "Brunei", nameEs: "Brun?i" },
  { iso2: "BG", dialCode: "359", nameEn: "Bulgaria", namePt: "Bulg?ria", nameEs: "Bulgaria" },
  { iso2: "BF", dialCode: "226", nameEn: "Burkina Faso", namePt: "Burkina Faso", nameEs: "Burkina Faso" },
  { iso2: "BI", dialCode: "257", nameEn: "Burundi", namePt: "Burundi", nameEs: "Burundi" },
  { iso2: "BT", dialCode: "975", nameEn: "Bhutan", namePt: "But?o", nameEs: "But?n" },
  { iso2: "CV", dialCode: "238", nameEn: "Cape Verde", namePt: "Cabo Verde", nameEs: "Cabo Verde" },
  { iso2: "CM", dialCode: "237", nameEn: "Cameroon", namePt: "Camar?es", nameEs: "Camer?n" },
  { iso2: "KH", dialCode: "855", nameEn: "Cambodia", namePt: "Camboja", nameEs: "Camboya" },
  { iso2: "CA", dialCode: "1", nameEn: "Canada", namePt: "Canad?", nameEs: "Canad?" },
  { iso2: "QA", dialCode: "974", nameEn: "Qatar", namePt: "Catar", nameEs: "Catar" },
  { iso2: "KZ", dialCode: "7", nameEn: "Kazakhstan", namePt: "Cazaquist?o", nameEs: "Kazajist?n" },
  { iso2: "TD", dialCode: "235", nameEn: "Chad", namePt: "Chade", nameEs: "Chad" },
  { iso2: "CL", dialCode: "56", nameEn: "Chile", namePt: "Chile", nameEs: "Chile" },
  { iso2: "CN", dialCode: "86", nameEn: "China", namePt: "China", nameEs: "China" },
  { iso2: "CY", dialCode: "357", nameEn: "Cyprus", namePt: "Chipre", nameEs: "Chipre" },
  { iso2: "CO", dialCode: "57", nameEn: "Colombia", namePt: "Col?mbia", nameEs: "Colombia" },
  { iso2: "KM", dialCode: "269", nameEn: "Comoros", namePt: "Comores", nameEs: "Comoras" },
  { iso2: "CG", dialCode: "242", nameEn: "Congo", namePt: "Congo", nameEs: "Congo" },
  { iso2: "CD", dialCode: "243", nameEn: "DR Congo", namePt: "Congo (RDC)", nameEs: "RD Congo" },
  { iso2: "KP", dialCode: "850", nameEn: "North Korea", namePt: "Coreia do Norte", nameEs: "Corea del Norte" },
  { iso2: "KR", dialCode: "82", nameEn: "South Korea", namePt: "Coreia do Sul", nameEs: "Corea del Sur" },
  { iso2: "CI", dialCode: "225", nameEn: "Ivory Coast", namePt: "Costa do Marfim", nameEs: "Costa de Marfil" },
  { iso2: "CR", dialCode: "506", nameEn: "Costa Rica", namePt: "Costa Rica", nameEs: "Costa Rica" },
  { iso2: "HR", dialCode: "385", nameEn: "Croatia", namePt: "Cro?cia", nameEs: "Croacia" },
  { iso2: "CU", dialCode: "53", nameEn: "Cuba", namePt: "Cuba", nameEs: "Cuba" },
  { iso2: "DK", dialCode: "45", nameEn: "Denmark", namePt: "Dinamarca", nameEs: "Dinamarca" },
  { iso2: "DJ", dialCode: "253", nameEn: "Djibouti", namePt: "Djibuti", nameEs: "Yibuti" },
  { iso2: "DM", dialCode: "1767", nameEn: "Dominica", namePt: "Dominica", nameEs: "Dominica" },
  { iso2: "EG", dialCode: "20", nameEn: "Egypt", namePt: "Egito", nameEs: "Egipto" },
  { iso2: "SV", dialCode: "503", nameEn: "El Salvador", namePt: "El Salvador", nameEs: "El Salvador" },
  { iso2: "AE", dialCode: "971", nameEn: "United Arab Emirates", namePt: "Emirados ?rabes Unidos", nameEs: "Emiratos ?rabes Unidos" },
  { iso2: "EC", dialCode: "593", nameEn: "Ecuador", namePt: "Equador", nameEs: "Ecuador" },
  { iso2: "ER", dialCode: "291", nameEn: "Eritrea", namePt: "Eritreia", nameEs: "Eritrea" },
  { iso2: "SK", dialCode: "421", nameEn: "Slovakia", namePt: "Eslov?quia", nameEs: "Eslovaquia" },
  { iso2: "SI", dialCode: "386", nameEn: "Slovenia", namePt: "Eslov?nia", nameEs: "Eslovenia" },
  { iso2: "ES", dialCode: "34", nameEn: "Spain", namePt: "Espanha", nameEs: "Espa?a" },
  { iso2: "US", dialCode: "1", nameEn: "United States", namePt: "Estados Unidos", nameEs: "Estados Unidos" },
  { iso2: "EE", dialCode: "372", nameEn: "Estonia", namePt: "Est?nia", nameEs: "Estonia" },
  { iso2: "SZ", dialCode: "268", nameEn: "Eswatini", namePt: "Essuat?ni", nameEs: "Esuatini" },
  { iso2: "ET", dialCode: "251", nameEn: "Ethiopia", namePt: "Eti?pia", nameEs: "Etiop?a" },
  { iso2: "FJ", dialCode: "679", nameEn: "Fiji", namePt: "Fiji", nameEs: "Fiyi" },
  { iso2: "PH", dialCode: "63", nameEn: "Philippines", namePt: "Filipinas", nameEs: "Filipinas" },
  { iso2: "FI", dialCode: "358", nameEn: "Finland", namePt: "Finl?ndia", nameEs: "Finlandia" },
  { iso2: "FR", dialCode: "33", nameEn: "France", namePt: "Fran?a", nameEs: "Francia" },
  { iso2: "GA", dialCode: "241", nameEn: "Gabon", namePt: "Gab?o", nameEs: "Gab?n" },
  { iso2: "GM", dialCode: "220", nameEn: "Gambia", namePt: "G?mbia", nameEs: "Gambia" },
  { iso2: "GH", dialCode: "233", nameEn: "Ghana", namePt: "Gana", nameEs: "Ghana" },
  { iso2: "GE", dialCode: "995", nameEn: "Georgia", namePt: "Ge?rgia", nameEs: "Georgia" },
  { iso2: "GR", dialCode: "30", nameEn: "Greece", namePt: "Gr?cia", nameEs: "Grecia" },
  { iso2: "GD", dialCode: "1473", nameEn: "Grenada", namePt: "Granada", nameEs: "Granada" },
  { iso2: "GT", dialCode: "502", nameEn: "Guatemala", namePt: "Guatemala", nameEs: "Guatemala" },
  { iso2: "GY", dialCode: "592", nameEn: "Guyana", namePt: "Guiana", nameEs: "Guyana" },
  { iso2: "GN", dialCode: "224", nameEn: "Guinea", namePt: "Guin?", nameEs: "Guinea" },
  { iso2: "GQ", dialCode: "240", nameEn: "Equatorial Guinea", namePt: "Guin? Equatorial", nameEs: "Guinea Ecuatorial" },
  { iso2: "GW", dialCode: "245", nameEn: "Guinea-Bissau", namePt: "Guin?-Bissau", nameEs: "Guinea-Bis?u" },
  { iso2: "HT", dialCode: "509", nameEn: "Haiti", namePt: "Haiti", nameEs: "Hait?" },
  { iso2: "HN", dialCode: "504", nameEn: "Honduras", namePt: "Honduras", nameEs: "Honduras" },
  { iso2: "HU", dialCode: "36", nameEn: "Hungary", namePt: "Hungria", nameEs: "Hungr?a" },
  { iso2: "YE", dialCode: "967", nameEn: "Yemen", namePt: "I?men", nameEs: "Yemen" },
  { iso2: "IN", dialCode: "91", nameEn: "India", namePt: "?ndia", nameEs: "India" },
  { iso2: "ID", dialCode: "62", nameEn: "Indonesia", namePt: "Indon?sia", nameEs: "Indonesia" },
  { iso2: "IQ", dialCode: "964", nameEn: "Iraq", namePt: "Iraque", nameEs: "Irak" },
  { iso2: "IR", dialCode: "98", nameEn: "Iran", namePt: "Ir?", nameEs: "Ir?n" },
  { iso2: "IE", dialCode: "353", nameEn: "Ireland", namePt: "Irlanda", nameEs: "Irlanda" },
  { iso2: "IS", dialCode: "354", nameEn: "Iceland", namePt: "Isl?ndia", nameEs: "Islandia" },
  { iso2: "IL", dialCode: "972", nameEn: "Israel", namePt: "Israel", nameEs: "Israel" },
  { iso2: "IT", dialCode: "39", nameEn: "Italy", namePt: "It?lia", nameEs: "Italia" },
  { iso2: "JM", dialCode: "1876", nameEn: "Jamaica", namePt: "Jamaica", nameEs: "Jamaica" },
  { iso2: "JP", dialCode: "81", nameEn: "Japan", namePt: "Jap?o", nameEs: "Jap?n" },
  { iso2: "JO", dialCode: "962", nameEn: "Jordan", namePt: "Jord?nia", nameEs: "Jordania" },
  { iso2: "KW", dialCode: "965", nameEn: "Kuwait", namePt: "Kuwait", nameEs: "Kuwait" },
  { iso2: "LA", dialCode: "856", nameEn: "Laos", namePt: "Laos", nameEs: "Laos" },
  { iso2: "LS", dialCode: "266", nameEn: "Lesotho", namePt: "Lesoto", nameEs: "Lesoto" },
  { iso2: "LV", dialCode: "371", nameEn: "Latvia", namePt: "Let?nia", nameEs: "Letonia" },
  { iso2: "LB", dialCode: "961", nameEn: "Lebanon", namePt: "L?bano", nameEs: "L?bano" },
  { iso2: "LR", dialCode: "231", nameEn: "Liberia", namePt: "Lib?ria", nameEs: "Liberia" },
  { iso2: "LY", dialCode: "218", nameEn: "Libya", namePt: "L?bia", nameEs: "Libia" },
  { iso2: "LI", dialCode: "423", nameEn: "Liechtenstein", namePt: "Liechtenstein", nameEs: "Liechtenstein" },
  { iso2: "LT", dialCode: "370", nameEn: "Lithuania", namePt: "Litu?nia", nameEs: "Lituania" },
  { iso2: "LU", dialCode: "352", nameEn: "Luxembourg", namePt: "Luxemburgo", nameEs: "Luxemburgo" },
  { iso2: "MK", dialCode: "389", nameEn: "North Macedonia", namePt: "Maced?nia do Norte", nameEs: "Macedonia del Norte" },
  { iso2: "MG", dialCode: "261", nameEn: "Madagascar", namePt: "Madagascar", nameEs: "Madagascar" },
  { iso2: "MY", dialCode: "60", nameEn: "Malaysia", namePt: "Mal?sia", nameEs: "Malasia" },
  { iso2: "MW", dialCode: "265", nameEn: "Malawi", namePt: "Malawi", nameEs: "Malaui" },
  { iso2: "MV", dialCode: "960", nameEn: "Maldives", namePt: "Maldivas", nameEs: "Maldivas" },
  { iso2: "ML", dialCode: "223", nameEn: "Mali", namePt: "Mali", nameEs: "Mali" },
  { iso2: "MT", dialCode: "356", nameEn: "Malta", namePt: "Malta", nameEs: "Malta" },
  { iso2: "MA", dialCode: "212", nameEn: "Morocco", namePt: "Marrocos", nameEs: "Marruecos" },
  { iso2: "MU", dialCode: "230", nameEn: "Mauritius", namePt: "Maur?cio", nameEs: "Mauricio" },
  { iso2: "MR", dialCode: "222", nameEn: "Mauritania", namePt: "Maurit?nia", nameEs: "Mauritania" },
  { iso2: "MX", dialCode: "52", nameEn: "Mexico", namePt: "M?xico", nameEs: "M?xico" },
  { iso2: "MM", dialCode: "95", nameEn: "Myanmar", namePt: "Mianmar", nameEs: "Myanmar" },
  { iso2: "FM", dialCode: "691", nameEn: "Micronesia", namePt: "Micron?sia", nameEs: "Micronesia" },
  { iso2: "MZ", dialCode: "258", nameEn: "Mozambique", namePt: "Mo?ambique", nameEs: "Mozambique" },
  { iso2: "MD", dialCode: "373", nameEn: "Moldova", namePt: "Mold?via", nameEs: "Moldavia" },
  { iso2: "MC", dialCode: "377", nameEn: "Monaco", namePt: "M?naco", nameEs: "M?naco" },
  { iso2: "MN", dialCode: "976", nameEn: "Mongolia", namePt: "Mong?lia", nameEs: "Mongolia" },
  { iso2: "ME", dialCode: "382", nameEn: "Montenegro", namePt: "Montenegro", nameEs: "Montenegro" },
  { iso2: "NA", dialCode: "264", nameEn: "Namibia", namePt: "Nam?bia", nameEs: "Namibia" },
  { iso2: "NR", dialCode: "674", nameEn: "Nauru", namePt: "Nauru", nameEs: "Nauru" },
  { iso2: "NP", dialCode: "977", nameEn: "Nepal", namePt: "Nepal", nameEs: "Nepal" },
  { iso2: "NI", dialCode: "505", nameEn: "Nicaragua", namePt: "Nicar?gua", nameEs: "Nicaragua" },
  { iso2: "NE", dialCode: "227", nameEn: "Niger", namePt: "N?ger", nameEs: "N?ger" },
  { iso2: "NG", dialCode: "234", nameEn: "Nigeria", namePt: "Nig?ria", nameEs: "Nigeria" },
  { iso2: "NO", dialCode: "47", nameEn: "Norway", namePt: "Noruega", nameEs: "Noruega" },
  { iso2: "NZ", dialCode: "64", nameEn: "New Zealand", namePt: "Nova Zel?ndia", nameEs: "Nueva Zelanda" },
  { iso2: "OM", dialCode: "968", nameEn: "Oman", namePt: "Om?", nameEs: "Om?n" },
  { iso2: "NL", dialCode: "31", nameEn: "Netherlands", namePt: "Pa?ses Baixos", nameEs: "Pa?ses Bajos" },
  { iso2: "PW", dialCode: "680", nameEn: "Palau", namePt: "Palau", nameEs: "Palaos" },
  { iso2: "PA", dialCode: "507", nameEn: "Panama", namePt: "Panam?", nameEs: "Panam?" },
  { iso2: "PG", dialCode: "675", nameEn: "Papua New Guinea", namePt: "Papua-Nova Guin?", nameEs: "Pap?a Nueva Guinea" },
  { iso2: "PK", dialCode: "92", nameEn: "Pakistan", namePt: "Paquist?o", nameEs: "Pakist?n" },
  { iso2: "PY", dialCode: "595", nameEn: "Paraguay", namePt: "Paraguai", nameEs: "Paraguay" },
  { iso2: "PE", dialCode: "51", nameEn: "Peru", namePt: "Peru", nameEs: "Per?" },
  { iso2: "PL", dialCode: "48", nameEn: "Poland", namePt: "Pol?nia", nameEs: "Polonia" },
  { iso2: "PT", dialCode: "351", nameEn: "Portugal", namePt: "Portugal", nameEs: "Portugal" },
  { iso2: "KE", dialCode: "254", nameEn: "Kenya", namePt: "Qu?nia", nameEs: "Kenia" },
  { iso2: "KG", dialCode: "996", nameEn: "Kyrgyzstan", namePt: "Quirguist?o", nameEs: "Kirguist?n" },
  { iso2: "GB", dialCode: "44", nameEn: "United Kingdom", namePt: "Reino Unido", nameEs: "Reino Unido" },
  { iso2: "CF", dialCode: "236", nameEn: "Central African Republic", namePt: "Rep?blica Centro-Africana", nameEs: "Rep?blica Centroafricana" },
  { iso2: "DO", dialCode: "1809", nameEn: "Dominican Republic", namePt: "Rep?blica Dominicana", nameEs: "Rep?blica Dominicana" },
  { iso2: "CZ", dialCode: "420", nameEn: "Czech Republic", namePt: "Rep?blica Tcheca", nameEs: "Rep?blica Checa" },
  { iso2: "RO", dialCode: "40", nameEn: "Romania", namePt: "Rom?nia", nameEs: "Rumania" },
  { iso2: "RW", dialCode: "250", nameEn: "Rwanda", namePt: "Ruanda", nameEs: "Ruanda" },
  { iso2: "RU", dialCode: "7", nameEn: "Russia", namePt: "R?ssia", nameEs: "Rusia" },
  { iso2: "WS", dialCode: "685", nameEn: "Samoa", namePt: "Samoa", nameEs: "Samoa" },
  { iso2: "SM", dialCode: "378", nameEn: "San Marino", namePt: "San Marino", nameEs: "San Marino" },
  { iso2: "LC", dialCode: "1758", nameEn: "Saint Lucia", namePt: "Santa L?cia", nameEs: "Santa Luc?a" },
  { iso2: "ST", dialCode: "239", nameEn: "S?o Tom? and Pr?ncipe", namePt: "S?o Tom? e Pr?ncipe", nameEs: "Santo Tom? y Pr?ncipe" },
  { iso2: "SN", dialCode: "221", nameEn: "Senegal", namePt: "Senegal", nameEs: "Senegal" },
  { iso2: "SL", dialCode: "232", nameEn: "Sierra Leone", namePt: "Serra Leoa", nameEs: "Sierra Leona" },
  { iso2: "RS", dialCode: "381", nameEn: "Serbia", namePt: "S?rvia", nameEs: "Serbia" },
  { iso2: "SC", dialCode: "248", nameEn: "Seychelles", namePt: "Seicheles", nameEs: "Seychelles" },
  { iso2: "SG", dialCode: "65", nameEn: "Singapore", namePt: "Singapura", nameEs: "Singapur" },
  { iso2: "SY", dialCode: "963", nameEn: "Syria", namePt: "S?ria", nameEs: "Siria" },
  { iso2: "SO", dialCode: "252", nameEn: "Somalia", namePt: "Som?lia", nameEs: "Somalia" },
  { iso2: "LK", dialCode: "94", nameEn: "Sri Lanka", namePt: "Sri Lanka", nameEs: "Sri Lanka" },
  { iso2: "SD", dialCode: "249", nameEn: "Sudan", namePt: "Sud?o", nameEs: "Sud?n" },
  { iso2: "SS", dialCode: "211", nameEn: "South Sudan", namePt: "Sud?o do Sul", nameEs: "Sud?n del Sur" },
  { iso2: "SE", dialCode: "46", nameEn: "Sweden", namePt: "Su?cia", nameEs: "Suecia" },
  { iso2: "CH", dialCode: "41", nameEn: "Switzerland", namePt: "Su??a", nameEs: "Suiza" },
  { iso2: "SR", dialCode: "597", nameEn: "Suriname", namePt: "Suriname", nameEs: "Surinam" },
  { iso2: "TH", dialCode: "66", nameEn: "Thailand", namePt: "Tail?ndia", nameEs: "Tailandia" },
  { iso2: "TW", dialCode: "886", nameEn: "Taiwan", namePt: "Taiwan", nameEs: "Taiw?n" },
  { iso2: "TJ", dialCode: "992", nameEn: "Tajikistan", namePt: "Tajiquist?o", nameEs: "Tayikist?n" },
  { iso2: "TZ", dialCode: "255", nameEn: "Tanzania", namePt: "Tanz?nia", nameEs: "Tanzania" },
  { iso2: "TL", dialCode: "670", nameEn: "Timor-Leste", namePt: "Timor-Leste", nameEs: "Timor Oriental" },
  { iso2: "TG", dialCode: "228", nameEn: "Togo", namePt: "Togo", nameEs: "Togo" },
  { iso2: "TO", dialCode: "676", nameEn: "Tonga", namePt: "Tonga", nameEs: "Tonga" },
  { iso2: "TT", dialCode: "1868", nameEn: "Trinidad and Tobago", namePt: "Trinidad e Tobago", nameEs: "Trinidad y Tobago" },
  { iso2: "TN", dialCode: "216", nameEn: "Tunisia", namePt: "Tun?sia", nameEs: "T?nez" },
  { iso2: "TM", dialCode: "993", nameEn: "Turkmenistan", namePt: "Turcomenist?o", nameEs: "Turkmenist?n" },
  { iso2: "TR", dialCode: "90", nameEn: "Turkey", namePt: "Turquia", nameEs: "Turqu?a" },
  { iso2: "TV", dialCode: "688", nameEn: "Tuvalu", namePt: "Tuvalu", nameEs: "Tuvalu" },
  { iso2: "UA", dialCode: "380", nameEn: "Ukraine", namePt: "Ucr?nia", nameEs: "Ucrania" },
  { iso2: "UG", dialCode: "256", nameEn: "Uganda", namePt: "Uganda", nameEs: "Uganda" },
  { iso2: "UY", dialCode: "598", nameEn: "Uruguay", namePt: "Uruguai", nameEs: "Uruguay" },
  { iso2: "UZ", dialCode: "998", nameEn: "Uzbekistan", namePt: "Uzbequist?o", nameEs: "Uzbekist?n" },
  { iso2: "VU", dialCode: "678", nameEn: "Vanuatu", namePt: "Vanuatu", nameEs: "Vanuatu" },
  { iso2: "VA", dialCode: "379", nameEn: "Vatican City", namePt: "Vaticano", nameEs: "Ciudad del Vaticano" },
  { iso2: "VE", dialCode: "58", nameEn: "Venezuela", namePt: "Venezuela", nameEs: "Venezuela" },
  { iso2: "VN", dialCode: "84", nameEn: "Vietnam", namePt: "Vietn?", nameEs: "Vietnam" },
  { iso2: "ZM", dialCode: "260", nameEn: "Zambia", namePt: "Z?mbia", nameEs: "Zambia" },
  { iso2: "ZW", dialCode: "263", nameEn: "Zimbabwe", namePt: "Zimb?bue", nameEs: "Zimbabue" },
];

export function phoneCountryLabel(c: PhoneCountry, lang: "pt" | "en" | "es"): string {
  if (lang === "pt") return c.namePt;
  if (lang === "es") return c.nameEs;
  return c.nameEn;
}

export function findPhoneCountryByDialCode(dialCode: string): PhoneCountry | undefined {
  const digits = dialCode.replace(/\D/g, "");
  return PHONE_COUNTRIES.find((c) => c.dialCode === digits);
}

export function findPhoneCountryByIso(iso2: string): PhoneCountry | undefined {
  return PHONE_COUNTRIES.find((c) => c.iso2 === iso2.toUpperCase());
}
