export type PhoneCountry = {
  iso2: string;
  dialCode: string;
  nameEn: string;
};

/** ITU calling codes ? sorted by country name (EN). */
export const PHONE_COUNTRIES: PhoneCountry[] = [
  { iso2: "AF", dialCode: "93", nameEn: "Afghanistan" },
  { iso2: "ZA", dialCode: "27", nameEn: "South Africa" },
  { iso2: "AL", dialCode: "355", nameEn: "Albania" },
  { iso2: "DE", dialCode: "49", nameEn: "Germany" },
  { iso2: "AD", dialCode: "376", nameEn: "Andorra" },
  { iso2: "AO", dialCode: "244", nameEn: "Angola" },
  { iso2: "SA", dialCode: "966", nameEn: "Saudi Arabia" },
  { iso2: "DZ", dialCode: "213", nameEn: "Algeria" },
  { iso2: "AR", dialCode: "54", nameEn: "Argentina" },
  { iso2: "AM", dialCode: "374", nameEn: "Armenia" },
  { iso2: "AU", dialCode: "61", nameEn: "Australia" },
  { iso2: "AT", dialCode: "43", nameEn: "Austria" },
  { iso2: "AZ", dialCode: "994", nameEn: "Azerbaijan" },
  { iso2: "BS", dialCode: "1242", nameEn: "Bahamas" },
  { iso2: "BD", dialCode: "880", nameEn: "Bangladesh" },
  { iso2: "BB", dialCode: "1246", nameEn: "Barbados" },
  { iso2: "BH", dialCode: "973", nameEn: "Bahrain" },
  { iso2: "BE", dialCode: "32", nameEn: "Belgium" },
  { iso2: "BZ", dialCode: "501", nameEn: "Belize" },
  { iso2: "BJ", dialCode: "229", nameEn: "Benin" },
  { iso2: "BY", dialCode: "375", nameEn: "Belarus" },
  { iso2: "BO", dialCode: "591", nameEn: "Bolivia" },
  { iso2: "BA", dialCode: "387", nameEn: "Bosnia and Herzegovina" },
  { iso2: "BW", dialCode: "267", nameEn: "Botswana" },
  { iso2: "BR", dialCode: "55", nameEn: "Brazil" },
  { iso2: "BN", dialCode: "673", nameEn: "Brunei" },
  { iso2: "BG", dialCode: "359", nameEn: "Bulgaria" },
  { iso2: "BF", dialCode: "226", nameEn: "Burkina Faso" },
  { iso2: "BI", dialCode: "257", nameEn: "Burundi" },
  { iso2: "BT", dialCode: "975", nameEn: "Bhutan" },
  { iso2: "CV", dialCode: "238", nameEn: "Cape Verde" },
  { iso2: "CM", dialCode: "237", nameEn: "Cameroon" },
  { iso2: "KH", dialCode: "855", nameEn: "Cambodia" },
  { iso2: "CA", dialCode: "1", nameEn: "Canada" },
  { iso2: "QA", dialCode: "974", nameEn: "Qatar" },
  { iso2: "KZ", dialCode: "7", nameEn: "Kazakhstan" },
  { iso2: "TD", dialCode: "235", nameEn: "Chad" },
  { iso2: "CL", dialCode: "56", nameEn: "Chile" },
  { iso2: "CN", dialCode: "86", nameEn: "China" },
  { iso2: "CY", dialCode: "357", nameEn: "Cyprus" },
  { iso2: "CO", dialCode: "57", nameEn: "Colombia" },
  { iso2: "KM", dialCode: "269", nameEn: "Comoros" },
  { iso2: "CG", dialCode: "242", nameEn: "Congo" },
  { iso2: "CD", dialCode: "243", nameEn: "DR Congo" },
  { iso2: "KP", dialCode: "850", nameEn: "North Korea" },
  { iso2: "KR", dialCode: "82", nameEn: "South Korea" },
  { iso2: "CI", dialCode: "225", nameEn: "Ivory Coast" },
  { iso2: "CR", dialCode: "506", nameEn: "Costa Rica" },
  { iso2: "HR", dialCode: "385", nameEn: "Croatia" },
  { iso2: "CU", dialCode: "53", nameEn: "Cuba" },
  { iso2: "DK", dialCode: "45", nameEn: "Denmark" },
  { iso2: "DJ", dialCode: "253", nameEn: "Djibouti" },
  { iso2: "DM", dialCode: "1767", nameEn: "Dominica" },
  { iso2: "EG", dialCode: "20", nameEn: "Egypt" },
  { iso2: "SV", dialCode: "503", nameEn: "El Salvador" },
  { iso2: "AE", dialCode: "971", nameEn: "United Arab Emirates" },
  { iso2: "EC", dialCode: "593", nameEn: "Ecuador" },
  { iso2: "ER", dialCode: "291", nameEn: "Eritrea" },
  { iso2: "SK", dialCode: "421", nameEn: "Slovakia" },
  { iso2: "SI", dialCode: "386", nameEn: "Slovenia" },
  { iso2: "ES", dialCode: "34", nameEn: "Spain" },
  { iso2: "US", dialCode: "1", nameEn: "United States" },
  { iso2: "EE", dialCode: "372", nameEn: "Estonia" },
  { iso2: "SZ", dialCode: "268", nameEn: "Eswatini" },
  { iso2: "ET", dialCode: "251", nameEn: "Ethiopia" },
  { iso2: "FJ", dialCode: "679", nameEn: "Fiji" },
  { iso2: "PH", dialCode: "63", nameEn: "Philippines" },
  { iso2: "FI", dialCode: "358", nameEn: "Finland" },
  { iso2: "FR", dialCode: "33", nameEn: "France" },
  { iso2: "GA", dialCode: "241", nameEn: "Gabon" },
  { iso2: "GM", dialCode: "220", nameEn: "Gambia" },
  { iso2: "GH", dialCode: "233", nameEn: "Ghana" },
  { iso2: "GE", dialCode: "995", nameEn: "Georgia" },
  { iso2: "GR", dialCode: "30", nameEn: "Greece" },
  { iso2: "GD", dialCode: "1473", nameEn: "Grenada" },
  { iso2: "GT", dialCode: "502", nameEn: "Guatemala" },
  { iso2: "GY", dialCode: "592", nameEn: "Guyana" },
  { iso2: "GN", dialCode: "224", nameEn: "Guinea" },
  { iso2: "GQ", dialCode: "240", nameEn: "Equatorial Guinea" },
  { iso2: "GW", dialCode: "245", nameEn: "Guinea-Bissau" },
  { iso2: "HT", dialCode: "509", nameEn: "Haiti" },
  { iso2: "HN", dialCode: "504", nameEn: "Honduras" },
  { iso2: "HU", dialCode: "36", nameEn: "Hungary" },
  { iso2: "YE", dialCode: "967", nameEn: "Yemen" },
  { iso2: "IN", dialCode: "91", nameEn: "India" },
  { iso2: "ID", dialCode: "62", nameEn: "Indonesia" },
  { iso2: "IQ", dialCode: "964", nameEn: "Iraq" },
  { iso2: "IR", dialCode: "98", nameEn: "Iran" },
  { iso2: "IE", dialCode: "353", nameEn: "Ireland" },
  { iso2: "IS", dialCode: "354", nameEn: "Iceland" },
  { iso2: "IL", dialCode: "972", nameEn: "Israel" },
  { iso2: "IT", dialCode: "39", nameEn: "Italy" },
  { iso2: "JM", dialCode: "1876", nameEn: "Jamaica" },
  { iso2: "JP", dialCode: "81", nameEn: "Japan" },
  { iso2: "JO", dialCode: "962", nameEn: "Jordan" },
  { iso2: "KW", dialCode: "965", nameEn: "Kuwait" },
  { iso2: "LA", dialCode: "856", nameEn: "Laos" },
  { iso2: "LS", dialCode: "266", nameEn: "Lesotho" },
  { iso2: "LV", dialCode: "371", nameEn: "Latvia" },
  { iso2: "LB", dialCode: "961", nameEn: "Lebanon" },
  { iso2: "LR", dialCode: "231", nameEn: "Liberia" },
  { iso2: "LY", dialCode: "218", nameEn: "Libya" },
  { iso2: "LI", dialCode: "423", nameEn: "Liechtenstein" },
  { iso2: "LT", dialCode: "370", nameEn: "Lithuania" },
  { iso2: "LU", dialCode: "352", nameEn: "Luxembourg" },
  { iso2: "MK", dialCode: "389", nameEn: "North Macedonia" },
  { iso2: "MG", dialCode: "261", nameEn: "Madagascar" },
  { iso2: "MY", dialCode: "60", nameEn: "Malaysia" },
  { iso2: "MW", dialCode: "265", nameEn: "Malawi" },
  { iso2: "MV", dialCode: "960", nameEn: "Maldives" },
  { iso2: "ML", dialCode: "223", nameEn: "Mali" },
  { iso2: "MT", dialCode: "356", nameEn: "Malta" },
  { iso2: "MA", dialCode: "212", nameEn: "Morocco" },
  { iso2: "MU", dialCode: "230", nameEn: "Mauritius" },
  { iso2: "MR", dialCode: "222", nameEn: "Mauritania" },
  { iso2: "MX", dialCode: "52", nameEn: "Mexico" },
  { iso2: "MM", dialCode: "95", nameEn: "Myanmar" },
  { iso2: "FM", dialCode: "691", nameEn: "Micronesia" },
  { iso2: "MZ", dialCode: "258", nameEn: "Mozambique" },
  { iso2: "MD", dialCode: "373", nameEn: "Moldova" },
  { iso2: "MC", dialCode: "377", nameEn: "Monaco" },
  { iso2: "MN", dialCode: "976", nameEn: "Mongolia" },
  { iso2: "ME", dialCode: "382", nameEn: "Montenegro" },
  { iso2: "NA", dialCode: "264", nameEn: "Namibia" },
  { iso2: "NR", dialCode: "674", nameEn: "Nauru" },
  { iso2: "NP", dialCode: "977", nameEn: "Nepal" },
  { iso2: "NI", dialCode: "505", nameEn: "Nicaragua" },
  { iso2: "NE", dialCode: "227", nameEn: "Niger" },
  { iso2: "NG", dialCode: "234", nameEn: "Nigeria" },
  { iso2: "NO", dialCode: "47", nameEn: "Norway" },
  { iso2: "NZ", dialCode: "64", nameEn: "New Zealand" },
  { iso2: "OM", dialCode: "968", nameEn: "Oman" },
  { iso2: "NL", dialCode: "31", nameEn: "Netherlands" },
  { iso2: "PW", dialCode: "680", nameEn: "Palau" },
  { iso2: "PA", dialCode: "507", nameEn: "Panama" },
  { iso2: "PG", dialCode: "675", nameEn: "Papua New Guinea" },
  { iso2: "PK", dialCode: "92", nameEn: "Pakistan" },
  { iso2: "PY", dialCode: "595", nameEn: "Paraguay" },
  { iso2: "PE", dialCode: "51", nameEn: "Peru" },
  { iso2: "PL", dialCode: "48", nameEn: "Poland" },
  { iso2: "PT", dialCode: "351", nameEn: "Portugal" },
  { iso2: "KE", dialCode: "254", nameEn: "Kenya" },
  { iso2: "KG", dialCode: "996", nameEn: "Kyrgyzstan" },
  { iso2: "GB", dialCode: "44", nameEn: "United Kingdom" },
  { iso2: "CF", dialCode: "236", nameEn: "Central African Republic" },
  { iso2: "DO", dialCode: "1809", nameEn: "Dominican Republic" },
  { iso2: "CZ", dialCode: "420", nameEn: "Czech Republic" },
  { iso2: "RO", dialCode: "40", nameEn: "Romania" },
  { iso2: "RW", dialCode: "250", nameEn: "Rwanda" },
  { iso2: "RU", dialCode: "7", nameEn: "Russia" },
  { iso2: "WS", dialCode: "685", nameEn: "Samoa" },
  { iso2: "SM", dialCode: "378", nameEn: "San Marino" },
  { iso2: "LC", dialCode: "1758", nameEn: "Saint Lucia" },
  { iso2: "ST", dialCode: "239", nameEn: "Sao Tome and Principe" },
  { iso2: "SN", dialCode: "221", nameEn: "Senegal" },
  { iso2: "SL", dialCode: "232", nameEn: "Sierra Leone" },
  { iso2: "RS", dialCode: "381", nameEn: "Serbia" },
  { iso2: "SC", dialCode: "248", nameEn: "Seychelles" },
  { iso2: "SG", dialCode: "65", nameEn: "Singapore" },
  { iso2: "SY", dialCode: "963", nameEn: "Syria" },
  { iso2: "SO", dialCode: "252", nameEn: "Somalia" },
  { iso2: "LK", dialCode: "94", nameEn: "Sri Lanka" },
  { iso2: "SD", dialCode: "249", nameEn: "Sudan" },
  { iso2: "SS", dialCode: "211", nameEn: "South Sudan" },
  { iso2: "SE", dialCode: "46", nameEn: "Sweden" },
  { iso2: "CH", dialCode: "41", nameEn: "Switzerland" },
  { iso2: "SR", dialCode: "597", nameEn: "Suriname" },
  { iso2: "TH", dialCode: "66", nameEn: "Thailand" },
  { iso2: "TW", dialCode: "886", nameEn: "Taiwan" },
  { iso2: "TJ", dialCode: "992", nameEn: "Tajikistan" },
  { iso2: "TZ", dialCode: "255", nameEn: "Tanzania" },
  { iso2: "TL", dialCode: "670", nameEn: "Timor-Leste" },
  { iso2: "TG", dialCode: "228", nameEn: "Togo" },
  { iso2: "TO", dialCode: "676", nameEn: "Tonga" },
  { iso2: "TT", dialCode: "1868", nameEn: "Trinidad and Tobago" },
  { iso2: "TN", dialCode: "216", nameEn: "Tunisia" },
  { iso2: "TM", dialCode: "993", nameEn: "Turkmenistan" },
  { iso2: "TR", dialCode: "90", nameEn: "Turkey" },
  { iso2: "TV", dialCode: "688", nameEn: "Tuvalu" },
  { iso2: "UA", dialCode: "380", nameEn: "Ukraine" },
  { iso2: "UG", dialCode: "256", nameEn: "Uganda" },
  { iso2: "UY", dialCode: "598", nameEn: "Uruguay" },
  { iso2: "UZ", dialCode: "998", nameEn: "Uzbekistan" },
  { iso2: "VU", dialCode: "678", nameEn: "Vanuatu" },
  { iso2: "VA", dialCode: "379", nameEn: "Vatican City" },
  { iso2: "VE", dialCode: "58", nameEn: "Venezuela" },
  { iso2: "VN", dialCode: "84", nameEn: "Vietnam" },
  { iso2: "ZM", dialCode: "260", nameEn: "Zambia" },
  { iso2: "ZW", dialCode: "263", nameEn: "Zimbabwe" },
];

const displayNamesCache = new Map<string, Intl.DisplayNames>();

function localeForLang(lang: "pt" | "en" | "es"): string {
  if (lang === "pt") return "pt-BR";
  if (lang === "es") return "es";
  return "en";
}

function regionDisplayNames(lang: "pt" | "en" | "es"): Intl.DisplayNames {
  const locale = localeForLang(lang);
  let cached = displayNamesCache.get(locale);
  if (!cached) {
    cached = new Intl.DisplayNames([locale], { type: "region" });
    displayNamesCache.set(locale, cached);
  }
  return cached;
}

export function phoneCountryLabel(c: PhoneCountry, lang: "pt" | "en" | "es"): string {
  try {
    return regionDisplayNames(lang).of(c.iso2) ?? c.nameEn;
  } catch {
    return c.nameEn;
  }
}

export function findPhoneCountryByDialCode(dialCode: string): PhoneCountry | undefined {
  const digits = dialCode.replace(/\D/g, "");
  return PHONE_COUNTRIES.find((c) => c.dialCode === digits);
}

export function findPhoneCountryByIso(iso2: string): PhoneCountry | undefined {
  return PHONE_COUNTRIES.find((c) => c.iso2 === iso2.toUpperCase());
}
