/** Saint Germain flower essences and compound formulas — Sistema Saint Germain. */

export interface FloralCatalogEntry {
  value: string;
  labelKey: string;
  indicationKey: string;
}

export const SAINT_GERMAIN_ESSENCES: FloralCatalogEntry[] = [
  { value: "sg_abies_lourdes", labelKey: "it.ref.sg.abiesLourdes", indicationKey: "it.ref.sg.abiesLourdesInd" },
  { value: "sg_abrico", labelKey: "it.ref.sg.abrico", indicationKey: "it.ref.sg.abricoInd" },
  { value: "sg_abundancia", labelKey: "it.ref.sg.abundancia", indicationKey: "it.ref.sg.abundanciaInd" },
  { value: "sg_alcachofra", labelKey: "it.ref.sg.alcachofra", indicationKey: "it.ref.sg.alcachofraInd" },
  { value: "sg_algodao", labelKey: "it.ref.sg.algodao", indicationKey: "it.ref.sg.algodaoInd" },
  { value: "sg_allium", labelKey: "it.ref.sg.allium", indicationKey: "it.ref.sg.alliumInd" },
  { value: "sg_aloe", labelKey: "it.ref.sg.aloe", indicationKey: "it.ref.sg.aloeInd" },
  { value: "sg_ameixa", labelKey: "it.ref.sg.ameixa", indicationKey: "it.ref.sg.ameixaInd" },
  { value: "sg_amygdalus", labelKey: "it.ref.sg.amygdalus", indicationKey: "it.ref.sg.amygdalusInd" },
  { value: "sg_anis", labelKey: "it.ref.sg.anis", indicationKey: "it.ref.sg.anisInd" },
  { value: "sg_arnica_silvestre", labelKey: "it.ref.sg.arnicaSilvestre", indicationKey: "it.ref.sg.arnicaSilvestreInd" },
  { value: "sg_aveia_selvagem", labelKey: "it.ref.sg.aveiaSelvagem", indicationKey: "it.ref.sg.aveiaSelvagemInd" },
  { value: "sg_bambusa", labelKey: "it.ref.sg.bambusa", indicationKey: "it.ref.sg.bambusaInd" },
  { value: "sg_begonia", labelKey: "it.ref.sg.begonia", indicationKey: "it.ref.sg.begoniaInd" },
  { value: "sg_boa_deusa", labelKey: "it.ref.sg.boaDeusa", indicationKey: "it.ref.sg.boaDeusaInd" },
  { value: "sg_boa_sorte", labelKey: "it.ref.sg.boaSorte", indicationKey: "it.ref.sg.boaSorteInd" },
  { value: "sg_bom_dia", labelKey: "it.ref.sg.bomDia", indicationKey: "it.ref.sg.bomDiaInd" },
  { value: "sg_canela", labelKey: "it.ref.sg.canela", indicationKey: "it.ref.sg.canelaInd" },
  { value: "sg_capim_luz", labelKey: "it.ref.sg.capimLuz", indicationKey: "it.ref.sg.capimLuzInd" },
  { value: "sg_capim_seda", labelKey: "it.ref.sg.capimSeda", indicationKey: "it.ref.sg.capimSedaInd" },
  { value: "sg_carrapichao", labelKey: "it.ref.sg.carrapichao", indicationKey: "it.ref.sg.carrapichaoInd" },
  { value: "sg_chapeu_sol", labelKey: "it.ref.sg.chapeuSol", indicationKey: "it.ref.sg.chapeuSolInd" },
  { value: "sg_cidreira", labelKey: "it.ref.sg.cidreira", indicationKey: "it.ref.sg.cidreiraInd" },
  { value: "sg_cocos", labelKey: "it.ref.sg.cocos", indicationKey: "it.ref.sg.cocosInd" },
  { value: "sg_coronarium", labelKey: "it.ref.sg.coronarium", indicationKey: "it.ref.sg.coronariumInd" },
  { value: "sg_curculigum", labelKey: "it.ref.sg.curculigum", indicationKey: "it.ref.sg.curculigumInd" },
  { value: "sg_dulcis", labelKey: "it.ref.sg.dulcis", indicationKey: "it.ref.sg.dulcisInd" },
  { value: "sg_embauba", labelKey: "it.ref.sg.embauba", indicationKey: "it.ref.sg.embaubaInd" },
  { value: "sg_erbum", labelKey: "it.ref.sg.erbum", indicationKey: "it.ref.sg.erbumInd" },
  { value: "sg_erianthum", labelKey: "it.ref.sg.erianthum", indicationKey: "it.ref.sg.erianthumInd" },
  { value: "sg_flor_branca", labelKey: "it.ref.sg.florBranca", indicationKey: "it.ref.sg.florBrancaInd" },
  { value: "sg_focum", labelKey: "it.ref.sg.focum", indicationKey: "it.ref.sg.focumInd" },
  { value: "sg_geranio", labelKey: "it.ref.sg.geranio", indicationKey: "it.ref.sg.geranioInd" },
  { value: "sg_gloxinia", labelKey: "it.ref.sg.gloxinia", indicationKey: "it.ref.sg.gloxiniaInd" },
  { value: "sg_goiaba", labelKey: "it.ref.sg.goiaba", indicationKey: "it.ref.sg.goiabaInd" },
  { value: "sg_gracilis", labelKey: "it.ref.sg.gracilis", indicationKey: "it.ref.sg.gracilisInd" },
  { value: "sg_grandiflora", labelKey: "it.ref.sg.grandiflora", indicationKey: "it.ref.sg.grandifloraInd" },
  { value: "sg_grevilea", labelKey: "it.ref.sg.grevilea", indicationKey: "it.ref.sg.grevileaInd" },
  { value: "sg_heliconia", labelKey: "it.ref.sg.heliconia", indicationKey: "it.ref.sg.heliconiaInd" },
  { value: "sg_incensum", labelKey: "it.ref.sg.incensum", indicationKey: "it.ref.sg.incensumInd" },
  { value: "sg_indica", labelKey: "it.ref.sg.indica", indicationKey: "it.ref.sg.indicaInd" },
  { value: "sg_ipe_roxo", labelKey: "it.ref.sg.ipeRoxo", indicationKey: "it.ref.sg.ipeRoxoInd" },
  { value: "sg_jasmim_madagascar", labelKey: "it.ref.sg.jasmimMadagascar", indicationKey: "it.ref.sg.jasmimMadagascarInd" },
  { value: "sg_laurus_nobilis", labelKey: "it.ref.sg.laurusNobilis", indicationKey: "it.ref.sg.laurusNobilisInd" },
  { value: "sg_lavanda", labelKey: "it.ref.sg.lavanda", indicationKey: "it.ref.sg.lavandaInd" },
  { value: "sg_leucantha", labelKey: "it.ref.sg.leucantha", indicationKey: "it.ref.sg.leucanthaInd" },
  { value: "sg_limao", labelKey: "it.ref.sg.limao", indicationKey: "it.ref.sg.limaoInd" },
  { value: "sg_lirio_paz", labelKey: "it.ref.sg.lirioPaz", indicationKey: "it.ref.sg.lirioPazInd" },
  { value: "sg_lirio_real", labelKey: "it.ref.sg.lirioReal", indicationKey: "it.ref.sg.lirioRealInd" },
  { value: "sg_lisiandra", labelKey: "it.ref.sg.lisiandra", indicationKey: "it.ref.sg.lisiandraInd" },
  { value: "sg_lotus_azul", labelKey: "it.ref.sg.lotusAzul", indicationKey: "it.ref.sg.lotusAzulInd" },
  { value: "sg_lotus_egito", labelKey: "it.ref.sg.lotusEgito", indicationKey: "it.ref.sg.lotusEgitoInd" },
  { value: "sg_lotus_magnolia", labelKey: "it.ref.sg.lotusMagnolia", indicationKey: "it.ref.sg.lotusMagnoliaInd" },
  { value: "sg_maca", labelKey: "it.ref.sg.maca", indicationKey: "it.ref.sg.macaInd" },
  { value: "sg_madressilva", labelKey: "it.ref.sg.madressilva", indicationKey: "it.ref.sg.madressilvaInd" },
  { value: "sg_mangifera", labelKey: "it.ref.sg.mangifera", indicationKey: "it.ref.sg.mangiferaInd" },
  { value: "sg_margarida", labelKey: "it.ref.sg.margarida", indicationKey: "it.ref.sg.margaridaInd" },
  { value: "sg_melissa", labelKey: "it.ref.sg.melissa", indicationKey: "it.ref.sg.melissaInd" },
  { value: "sg_mimosinha", labelKey: "it.ref.sg.mimosinha", indicationKey: "it.ref.sg.mimosinhaInd" },
  { value: "sg_monterey", labelKey: "it.ref.sg.monterey", indicationKey: "it.ref.sg.montereyInd" },
  { value: "sg_myrtus", labelKey: "it.ref.sg.myrtus", indicationKey: "it.ref.sg.myrtusInd" },
  { value: "sg_oliva_fatima", labelKey: "it.ref.sg.olivaFatima", indicationKey: "it.ref.sg.olivaFatimaInd" },
  { value: "sg_panicum", labelKey: "it.ref.sg.panicum", indicationKey: "it.ref.sg.panicumInd" },
  { value: "sg_patiens", labelKey: "it.ref.sg.patiens", indicationKey: "it.ref.sg.patiensInd" },
  { value: "sg_pau_brasil", labelKey: "it.ref.sg.pauBrasil", indicationKey: "it.ref.sg.pauBrasilInd" },
  { value: "sg_pectus", labelKey: "it.ref.sg.pectus", indicationKey: "it.ref.sg.pectusInd" },
  { value: "sg_pepo", labelKey: "it.ref.sg.pepo", indicationKey: "it.ref.sg.pepoInd" },
  { value: "sg_perpetua", labelKey: "it.ref.sg.perpetua", indicationKey: "it.ref.sg.perpetuaInd" },
  { value: "sg_pinheiro_liberacao", labelKey: "it.ref.sg.pinheiroLiberacao", indicationKey: "it.ref.sg.pinheiroLiberacaoInd" },
  { value: "sg_piper", labelKey: "it.ref.sg.piper", indicationKey: "it.ref.sg.piperInd" },
  { value: "sg_poaia_rosa", labelKey: "it.ref.sg.poaiaRosa", indicationKey: "it.ref.sg.poaiaRosaInd" },
  { value: "sg_populus_panicum", labelKey: "it.ref.sg.populusPanicum", indicationKey: "it.ref.sg.populusPanicumInd" },
  { value: "sg_purpureum", labelKey: "it.ref.sg.purpureum", indicationKey: "it.ref.sg.purpureumInd" },
  { value: "sg_rosa_rosa", labelKey: "it.ref.sg.rosaRosa", indicationKey: "it.ref.sg.rosaRosaInd" },
  { value: "sg_saint_germain", labelKey: "it.ref.sg.saintGermain", indicationKey: "it.ref.sg.saintGermainInd" },
  { value: "sg_sao_miguel", labelKey: "it.ref.sg.saoMiguel", indicationKey: "it.ref.sg.saoMiguelInd" },
  { value: "sg_sapientum", labelKey: "it.ref.sg.sapientum", indicationKey: "it.ref.sg.sapientumInd" },
  { value: "sg_scorpius", labelKey: "it.ref.sg.scorpius", indicationKey: "it.ref.sg.scorpiusInd" },
  { value: "sg_sergipe", labelKey: "it.ref.sg.sergipe", indicationKey: "it.ref.sg.sergipeInd" },
  { value: "sg_sorgo", labelKey: "it.ref.sg.sorgo", indicationKey: "it.ref.sg.sorgoInd" },
  { value: "sg_thea", labelKey: "it.ref.sg.thea", indicationKey: "it.ref.sg.theaInd" },
  { value: "sg_tuia", labelKey: "it.ref.sg.tuia", indicationKey: "it.ref.sg.tuiaInd" },
  { value: "sg_triunfo", labelKey: "it.ref.sg.triunfo", indicationKey: "it.ref.sg.triunfoInd" },
  { value: "sg_umbellata", labelKey: "it.ref.sg.umbellata", indicationKey: "it.ref.sg.umbellataInd" },
  { value: "sg_unitatum", labelKey: "it.ref.sg.unitatum", indicationKey: "it.ref.sg.unitatumInd" },
  { value: "sg_varus", labelKey: "it.ref.sg.varus", indicationKey: "it.ref.sg.varusInd" },
  { value: "sg_verbena", labelKey: "it.ref.sg.verbena", indicationKey: "it.ref.sg.verbenaInd" },
  { value: "sg_vitoria", labelKey: "it.ref.sg.vitoria", indicationKey: "it.ref.sg.vitoriaInd" },
  { value: "sg_wedelia", labelKey: "it.ref.sg.wedelia", indicationKey: "it.ref.sg.wedeliaInd" },
];

export const SAINT_GERMAIN_COMPOUND_FORMULAS: FloralCatalogEntry[] = [
  { value: "sgf_emergencial", labelKey: "it.ref.sgf.emergencial", indicationKey: "it.ref.sgf.emergencialInd" },
  { value: "sgf_animo_equilibrio", labelKey: "it.ref.sgf.animoEquilibrio", indicationKey: "it.ref.sgf.animoEquilibrioInd" },
  { value: "sgf_anti_estresse", labelKey: "it.ref.sgf.antiEstresse", indicationKey: "it.ref.sgf.antiEstresseInd" },
  { value: "sgf_auto_estima", labelKey: "it.ref.sgf.autoEstima", indicationKey: "it.ref.sgf.autoEstimaInd" },
  { value: "sgf_bom_sono", labelKey: "it.ref.sgf.bomSono", indicationKey: "it.ref.sgf.bomSonoInd" },
  { value: "sgf_calma", labelKey: "it.ref.sgf.calma", indicationKey: "it.ref.sgf.calmaInd" },
  { value: "sgf_detox", labelKey: "it.ref.sgf.detox", indicationKey: "it.ref.sgf.detoxInd" },
  { value: "sgf_espiritualidade", labelKey: "it.ref.sgf.espiritualidade", indicationKey: "it.ref.sgf.espiritualidadeInd" },
  { value: "sgf_estudante", labelKey: "it.ref.sgf.estudante", indicationKey: "it.ref.sgf.estudanteInd" },
  { value: "sgf_integracao_familiar", labelKey: "it.ref.sgf.integracaoFamiliar", indicationKey: "it.ref.sgf.integracaoFamiliarInd" },
  { value: "sgf_leucantha", labelKey: "it.ref.sgf.leucantha", indicationKey: "it.ref.sgf.leucanthaInd" },
  { value: "sgf_meia_idade", labelKey: "it.ref.sgf.meiaIdade", indicationKey: "it.ref.sgf.meiaIdadeInd" },
  { value: "sgf_panicum", labelKey: "it.ref.sgf.panicum", indicationKey: "it.ref.sgf.panicumInd" },
  { value: "sgf_prosperidade", labelKey: "it.ref.sgf.prosperidade", indicationKey: "it.ref.sgf.prosperidadeInd" },
  { value: "sgf_protecao", labelKey: "it.ref.sgf.protecao", indicationKey: "it.ref.sgf.protecaoInd" },
  { value: "sgf_ansiedade", labelKey: "it.ref.sgf.ansiedade", indicationKey: "it.ref.sgf.ansiedadeInd" },
];

export function saintGermainEssenceByValue(value: string) {
  return SAINT_GERMAIN_ESSENCES.find((e) => e.value === value);
}

export function saintGermainFormulaByValue(value: string) {
  return SAINT_GERMAIN_COMPOUND_FORMULAS.find((e) => e.value === value);
}
