import type { ConsultTemplate } from "./types";

export const ACUPUNTURA_TEMPLATE: ConsultTemplate = {
  slug: "acupuntura",
  emptyValues: () => ({
    clinicalDiagnosis: "",
    mtcDiagnosis: "",
    tongueInspection: "",
    pulsePalpation: "",
    pointsSelected: "",
    technique_needling: false,
    technique_cupping: false,
    technique_moxa: false,
    technique_electro: false,
    technique_laser: false,
    retentionMins: "",
    sessionNumber: "",
    totalSessionsPlanned: "12",
    dietaryOrientations: "",
    prognosis: "",
    contraindicationsCleared: false,
    additionalNotes: "",
  }),
  fields: [
    { key: "clinicalDiagnosis", labelKey: "it.tpl.acu.clinicalDx", type: "text", sectionKey: "it.tpl.section.assessment" },
    { key: "mtcDiagnosis", labelKey: "it.tpl.acu.mtcDx", type: "textarea", sectionKey: "it.tpl.section.assessment", rows: 2 },
    { key: "tongueInspection", labelKey: "it.tpl.acu.tongue", type: "textarea", sectionKey: "it.tpl.section.assessment", rows: 2 },
    { key: "pulsePalpation", labelKey: "it.tpl.acu.pulse", type: "textarea", sectionKey: "it.tpl.section.assessment", rows: 2 },
    { key: "pointsSelected", labelKey: "it.tpl.acu.points", type: "textarea", sectionKey: "it.tpl.section.intervention", rows: 3 },
    { key: "technique_needling", labelKey: "it.tpl.acu.techNeedling", type: "checkbox", sectionKey: "it.tpl.section.intervention" },
    { key: "technique_cupping", labelKey: "it.tpl.acu.techCupping", type: "checkbox", sectionKey: "it.tpl.section.intervention" },
    { key: "technique_moxa", labelKey: "it.tpl.acu.techMoxa", type: "checkbox", sectionKey: "it.tpl.section.intervention" },
    { key: "technique_electro", labelKey: "it.tpl.acu.techElectro", type: "checkbox", sectionKey: "it.tpl.section.intervention" },
    { key: "technique_laser", labelKey: "it.tpl.acu.techLaser", type: "checkbox", sectionKey: "it.tpl.section.intervention" },
    { key: "retentionMins", labelKey: "it.tpl.acu.retention", type: "number", sectionKey: "it.tpl.section.intervention", placeholderKey: "it.tpl.acu.retentionHint" },
    { key: "sessionNumber", labelKey: "it.tpl.acu.sessionNum", type: "number", sectionKey: "it.tpl.section.plan" },
    { key: "totalSessionsPlanned", labelKey: "it.tpl.acu.totalSessions", type: "number", sectionKey: "it.tpl.section.plan" },
    { key: "dietaryOrientations", labelKey: "it.tpl.acu.diet", type: "textarea", sectionKey: "it.tpl.section.plan", rows: 2 },
    { key: "prognosis", labelKey: "it.tpl.common.prognosis", type: "textarea", sectionKey: "it.tpl.section.plan", rows: 2 },
    { key: "contraindicationsCleared", labelKey: "it.tpl.acu.contraindications", type: "checkbox", sectionKey: "it.tpl.section.plan" },
    { key: "additionalNotes", labelKey: "it.tpl.common.additional", type: "textarea", sectionKey: "it.tpl.section.notes", rows: 2 },
  ],
};
