// src/app/api/patient/history/pdf/route.ts
// Generates a printable HTML page that the browser renders as PDF
// Patient can print → Save as PDF from any browser

import { NextResponse } from "next/server";
import { requirePatient, isApiError } from "@/lib/api-auth";
import { db } from "@/lib/db";
import { audit } from "@/lib/audit";
import { decrypt } from "@/lib/encryption";
import { getAppUrl } from "@/lib/email-core";
import { printBrandLogoImg } from "@/lib/brand";

export async function GET() {
  const ctx = await requirePatient();
  if (isApiError(ctx)) return ctx.error;
  const { userId } = ctx;

  const patient = await db.patientProfile.findUnique({
    where: { userId },
    include: {
      medications: {
        where: { active: true, flow: "CLINICAL" },
        orderBy: { createdAt: "asc" },
      },
    },
  });

  if (!patient) return new NextResponse("Not found", { status: 404 });

  await audit.exportData(userId);

  const firstName = decrypt(patient.firstName);
  const lastName = decrypt(patient.lastName);
  const allergies = patient.allergies ? decrypt(patient.allergies) : "None reported";
  const chronicConditions = patient.chronicConditions ? decrypt(patient.chronicConditions) : "None reported";

  const medications = patient.medications.map((m) => ({
    name: decrypt(m.name),
    dosage: m.dosage ? decrypt(m.dosage) : "—",
    frequency: m.frequency ? decrypt(m.frequency) : "—",
    prescribedBy: m.prescribedBy || "—",
  }));

  const today = new Date().toLocaleDateString("en-US", {
    year: "numeric", month: "long", day: "numeric",
  });

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Medical Record — ${firstName} ${lastName}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, sans-serif; font-size: 13px; color: #1a1a1a; padding: 40px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 2px solid #0a4d6e; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-size: 28px; font-weight: 900; color: #0a4d6e; }
  .logo span { color: #00b87a; }
  .meta { text-align: right; font-size: 11px; color: #666; }
  .patient-name { font-size: 22px; font-weight: 700; color: #0a4d6e; margin-bottom: 4px; }
  .section { margin-bottom: 24px; }
  .section-title { font-size: 13px; font-weight: 700; color: #0a4d6e; text-transform: uppercase; letter-spacing: .05em; border-left: 3px solid #00b87a; padding-left: 8px; margin-bottom: 10px; }
  .field { margin-bottom: 8px; }
  .field-label { font-size: 11px; font-weight: 600; color: #666; text-transform: uppercase; letter-spacing: .04em; }
  .field-value { font-size: 13px; color: #1a1a1a; margin-top: 2px; line-height: 1.5; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; }
  th { background: #0a4d6e; color: white; padding: 8px 12px; text-align: left; font-weight: 600; font-size: 11px; }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f8fafc; }
  .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 12px; font-size: 10px; color: #999; text-align: center; }
  .confidential { background: #fff3cd; border: 1px solid #ffc107; border-radius: 4px; padding: 8px 12px; font-size: 11px; margin-bottom: 24px; }
  @media print {
    body { padding: 20px; }
    @page { margin: 1cm; }
  }
</style>
</head>
<body>

<div class="header">
  <div>
    <div class="logo">${printBrandLogoImg(getAppUrl())}</div>
    <div style="font-size:11px;color:#666;margin-top:4px;">Secure Health Platform</div>
  </div>
  <div class="meta">
    <div><strong>Patient Medical Record</strong></div>
    <div>Generated: ${today}</div>
    <div>Confidential — HIPAA Protected</div>
  </div>
</div>

<div class="confidential">
  ⚠️ CONFIDENTIAL — This document contains protected health information (PHI) covered under HIPAA.
  Unauthorized disclosure is prohibited. Document generated by the patient on ${today}.
</div>

<div class="patient-name">${firstName} ${lastName}</div>
<div style="font-size:12px;color:#666;margin-bottom:24px;">
  Blood type: <strong>${patient.bloodType || "Unknown"}</strong>
</div>

<div class="section">
  <div class="section-title">Allergies</div>
  <div class="field-value">${allergies}</div>
</div>

<div class="section">
  <div class="section-title">Chronic Conditions</div>
  <div class="field-value">${chronicConditions}</div>
</div>

<div class="section">
  <div class="section-title">Active Medications (Clinical)</div>
  ${medications.length === 0
    ? '<p style="color:#666;font-size:12px;">No active medications recorded.</p>'
    : `<table>
        <thead>
          <tr>
            <th>Medication</th>
            <th>Dosage</th>
            <th>Frequency</th>
            <th>Prescribed by</th>
          </tr>
        </thead>
        <tbody>
          ${medications.map((m) => `
            <tr>
              <td>${m.name}</td>
              <td>${m.dosage}</td>
              <td>${m.frequency}</td>
              <td>${m.prescribedBy}</td>
            </tr>
          `).join("")}
        </tbody>
      </table>`
  }
</div>

<div class="footer">
  This record was self-reported by the patient and may not reflect a complete clinical history.
  Doctor8 is a HIPAA &amp; GDPR compliant platform. doctor8.app
</div>

<script>
  window.onload = function() { window.print(); }
</script>

</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
