import { NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";
import { audit } from "@/lib/audit";
import { decrypt } from "@/lib/encryption";
import { getAppUrl } from "@/lib/email-core";
import { printBrandLogoImg } from "@/lib/brand";

function esc(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

type Lang = "pt" | "en" | "es";

const LABELS: Record<Lang, {
  title: string;
  subtitle: string;
  generated: string;
  clinical: string;
  clinicalEmpty: string;
  purchase: string;
  purchaseEmpty: string;
  med: string;
  dose: string;
  freq: string;
  prescriber: string;
  presentation: string;
  notes: string;
  footer: string;
}> = {
  pt: {
    title: "Medicamentos",
    subtitle: "Lista de medicamentos",
    generated: "Gerado em",
    clinical: "Medicamentos cl\u00ednicos",
    clinicalEmpty: "Nenhum medicamento cl\u00ednico ativo.",
    purchase: "Lista pessoal / refer\u00eancia CMED",
    purchaseEmpty: "Nenhum item na lista pessoal.",
    med: "Medicamento",
    dose: "Dose",
    freq: "Frequ\u00eancia",
    prescriber: "Prescrito por",
    presentation: "Apresenta\u00e7\u00e3o",
    notes: "Notas",
    footer: "Documento gerado pelo paciente \u00b7 Doctor8 \u00b7 Informa\u00e7\u00e3o confidencial (LGPD/HIPAA)",
  },
  en: {
    title: "Medications",
    subtitle: "Medication list",
    generated: "Generated on",
    clinical: "Clinical medications",
    clinicalEmpty: "No active clinical medications.",
    purchase: "Personal list / CMED reference",
    purchaseEmpty: "No items in personal list.",
    med: "Medication",
    dose: "Dose",
    freq: "Frequency",
    prescriber: "Prescribed by",
    presentation: "Presentation",
    notes: "Notes",
    footer: "Document generated by patient \u00b7 Doctor8 \u00b7 Confidential (LGPD/HIPAA)",
  },
  es: {
    title: "Medicamentos",
    subtitle: "Lista de medicamentos",
    generated: "Generado el",
    clinical: "Medicamentos cl\u00ednicos",
    clinicalEmpty: "Ning\u00fan medicamento cl\u00ednico activo.",
    purchase: "Lista personal / referencia CMED",
    purchaseEmpty: "Ning\u00fan item en la lista personal.",
    med: "Medicamento",
    dose: "Dosis",
    freq: "Frecuencia",
    prescriber: "Prescrito por",
    presentation: "Presentaci\u00f3n",
    notes: "Notas",
    footer: "Documento generado por el paciente \u00b7 Doctor8 \u00b7 Informaci\u00f3n confidencial (LGPD/HIPAA)",
  },
};

const LOCALE: Record<Lang, string> = { pt: "pt-BR", en: "en-US", es: "es-ES" };

function normLang(v: string | null | undefined): Lang {
  if (v === "pt" || v === "es") return v;
  return "en";
}

export async function GET() {
  const session = await auth();
  if (!session?.user) return new NextResponse("Unauthorized", { status: 401 });

  const user = await db.user.findUnique({
    where: { id: session.user.id },
    select: { language: true },
  });
  const lang = normLang(user?.language);
  const L = LABELS[lang];
  const locale = LOCALE[lang];

  const patient = await db.patientProfile.findUnique({
    where: { userId: session.user.id },
    include: {
      medications: {
        where: { active: true },
        orderBy: [{ flow: "asc" }, { createdAt: "desc" }],
      },
    },
  });

  if (!patient) return new NextResponse("Not found", { status: 404 });

  await audit.exportData(session.user.id);

  const firstName = decrypt(patient.firstName);
  const lastName = decrypt(patient.lastName);

  const medications = patient.medications;
  type MedicationItem = (typeof medications)[number];
  const clinical = medications.filter((m) => m.flow === "CLINICAL");
  const purchase = medications.filter((m) => m.flow === "PURCHASE");

  function clinicalRow(m: MedicationItem) {
    return `<tr>
      <td>${esc(decrypt(m.name))}</td>
      <td>${esc(m.dosage ? decrypt(m.dosage) : "\u2014")}</td>
      <td>${esc(m.frequency ? decrypt(m.frequency) : "\u2014")}</td>
      <td>${esc(m.prescribedBy || "\u2014")}</td>
    </tr>`;
  }

  function purchaseRow(m: MedicationItem) {
    return `<tr>
      <td>${esc(decrypt(m.name))}</td>
      <td>${esc(m.dosage ? decrypt(m.dosage) : "\u2014")}</td>
      <td>${esc(m.frequency ? decrypt(m.frequency) : "\u2014")}</td>
      <td>${esc(m.prescribedBy || "\u2014")}</td>
    </tr>`;
  }

  const today = new Date().toLocaleDateString(locale, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const html = `<!DOCTYPE html>
<html lang="${lang}">
<head>
<meta charset="UTF-8">
<title>${L.title} \u2014 ${esc(firstName)} ${esc(lastName)}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: Arial, sans-serif; font-size: 13px; color: #1a1a1a; padding: 40px; }
  .header { display: flex; justify-content: space-between; border-bottom: 2px solid #0a4d6e; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-size: 28px; font-weight: 900; color: #0a4d6e; }
  .logo span { color: #00b87a; }
  .section { margin-bottom: 24px; }
  .section-title { font-size: 13px; font-weight: 700; color: #0a4d6e; text-transform: uppercase; letter-spacing: .05em; border-left: 3px solid #00b87a; padding-left: 8px; margin-bottom: 10px; }
  table { width: 100%; border-collapse: collapse; font-size: 12px; margin-top: 8px; }
  th { background: #0a4d6e; color: white; padding: 8px 12px; text-align: left; }
  td { padding: 8px 12px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f8fafc; }
  .empty { color: #666; font-size: 12px; }
  .footer { margin-top: 40px; border-top: 1px solid #e5e7eb; padding-top: 12px; font-size: 10px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } @page { margin: 1cm; } }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="logo">${printBrandLogoImg(getAppUrl())}</div>
    <div style="font-size:11px;color:#666;margin-top:4px;">${L.subtitle}</div>
  </div>
  <div style="text-align:right;font-size:11px;color:#666;">
    <div><strong>${esc(firstName)} ${esc(lastName)}</strong></div>
    <div>${L.generated} ${esc(today)}</div>
  </div>
</div>

<div class="section">
  <div class="section-title">${L.clinical}</div>
  ${
    clinical.length === 0
      ? `<p class="empty">${L.clinicalEmpty}</p>`
      : `<table><thead><tr><th>${L.med}</th><th>${L.dose}</th><th>${L.freq}</th><th>${L.prescriber}</th></tr></thead><tbody>${clinical.map(clinicalRow).join("")}</tbody></table>`
  }
</div>

<div class="section">
  <div class="section-title">${L.purchase}</div>
  ${
    purchase.length === 0
      ? `<p class="empty">${L.purchaseEmpty}</p>`
      : `<table><thead><tr><th>${L.med}</th><th>${L.presentation}</th><th>${L.notes}</th><th>${L.prescriber}</th></tr></thead><tbody>${purchase.map(purchaseRow).join("")}</tbody></table>`
  }
</div>

<div class="footer">${L.footer}</div>
<script>window.onload=function(){window.print();}</script>
</body>
</html>`;

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
